* Archlinux(gnome desktop)
** grub

 - 按照网上教程走，如果双系统（win10在c盘，archlinux在d盘）在grub-...(忘了)，就是写配置文件的时候（非grub-install）没有发现win的启动项,
不用慌，你可以重启再写一次，如果还没有，可以先装好桌面环境，之后再执行一次，就有了。（我不知道原理）

** electric-ssr

 - 装好ssr，写入订阅链接，再次打开没有GUI界面(用terminal在打开一次)，这是正常现象，你之后是可以访问外网的。

** gnome-extensions

 - 如果无法通过网页——gnome-extensions安装插件，不用慌，可以使用桌面上的 商店 进行安装。推荐插件
user-Theme dask-to-dock

** fcitx

 - 安装fcitx-im fcitx-*tools 以及输入法
 - 新建文件 .pam_environment
 - 在新文件里写入以下三行内容(其他系统可能是什么 .xprofile文件)
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx

* 设置 china 镜像源(软件安装更快)

sudo pacman-mirrors -i -c China -m rank
一会儿会弹出一个交互窗口，选择你想使用的镜像源(最好选择多个)

* 添加 archlinuxCN 源

sudo gedit  /etc/pacman.conf or sudo nano /etc/pacman.conf

在文件底部添加以下内容 这是中科大的源


[arch4edu]
SigLevel = TrustAll
Server = https://mirrors.tuna.tsinghua.edu.cn/arch4edu/$arch
[archlinuxcn]
SigLevel = TrustAll
Server = https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/$arch
Server = https://mirrors.ustc.edu.cn/archlinuxcn/$arch　
Server = http://repo.archlinuxcn.org/$arch
[antergos]
SigLevel = TrustAll
Server = https://mirrors.tuna.tsinghua.edu.cn/antergos/$repo/$arch
Server = https://mirrors.ustc.edu.cn/antergos/$repo/$arch

then

sudo pacman -Syy && sudo pacman -S archlinuxcn-keyring

* 更新，解决时间问题(双系统)

安装aur包管理器yay(yaourt 已经停止维护了，用这个来安装非官方发行软件)

sudo pacman -S yay

Manjaro系统和windows系统时间差8个小时，解决该问题。

操作  Manjaro Settings Manager -> Time and Date  勾上 Set time and automatically

备用方案：sudo timedatectl set-local-rtc 1

* 中文输入法—需要重启(sogoupinyin)

sudo pacman -S fcitx-im fcitx-configtool fcitx-sogoupinyin

修改配置文件

sudo gedit ~/.xprofile

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"

* 文泉驿等宽微米黑字体

sudo pacman -S wqy-microhei

* 一些常用的软件

sudo pacman -S google-chrome shadowsocks-qt5 netease-cloud-music pandoc electronic-wechat tree deepin-screenshot albert

yay -S visual-studio-code-bin wps-office ttf-wps-fonts mpv nautilus

* ZSH

# 首先是安装 zsh
sudo pacman -S zsh

# 接着配置 oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# 更换主题
ZSH_THEME="bira"

# 最后更换默认的 shell
chsh -s /bin/zsh

* sdcv

这是一个查英语单词意思的一个插件。
 - [ ] 安装sdcv stardict(such as sudo apt-get install sdcv stardict)

Arch or Manjaro 使用下面的安装命令可以安装
sudo pacman -S sdcv stardict

 - [ ] 下载一些词典，[[http://download.huzheng.org/zh_CN/][链接]]，（我下载的是什么懒虫简明字典）并将词典放在目录(setq sdcv-dictionary-data-dir "_/usr/share/stardict/dic_")，要先解压缩，再放进去。
 - [ ] 快捷键的设置在config文件中最后一行（我的快捷键C-c t）

* Ag

ag 指的是 the_silver_searcher
Arch or Manjaro 使用下面的安装命令可以安装
sudo pacman -S the_silver_searcher

* Rg

sudo pacman -S ripgrep

* Aspell

sudo pacman -S aspell aspell-en

* 美化

# GTK3 and shell
Mojave-dark

# icons
Numix-circle

* 如何在 Manjaro里 安装 appimage 包

1) chmod +x /path/to/file ;; 为需要安装的软件给予权限

2) 鼠标双击软件就可以安装了

* 谷歌插件

- 谷歌助手破解版

https://github.com/haotian-wang/google-access-helper

- Proxy SwitchyOmega
