* 大学生心理健康

              认识自己
    本来打着检验自己心理是否健康的想法选修的这门课程，没想到的是，这门课上着上着还有一些意外的收货。
    在大学生恋爱问题的课程中讲到，男女心理是有差异的，但是在这儿，反过来，我并没有谈特定的男女关系如何处理，而是从中引申出来，我想谈谈如何同
其他人打好关系的问题，谈谈一些共性的问题，可能这并不属于心理学范畴。
    首先，我们先培养一些共同的爱好，创造出属于双方独特的记忆开始吧！为什们要这么说呢？这样说吧，你有见过喜欢宅在家里的人和喜欢运动的人待在一起吗？没有吧。当然，这只
是一个假设，只是为了说明没有一些共同的爱好或者一些共有特征的话是没法走在一起的，在没有一些共有特征的基础上就想让对方接纳自己，这是很困难
的，同时，这更是强人所难、无理的要求。不过，与此相反，如果是两个非常开朗的人或者内向的人就很容易敞开心扉，接纳对方。因为他们一开始就有了一些共有
特征，开朗和内向。因为有着一些共有特征，就很容易从对方找到一种亲切感、归属感，就好像从对方看见了自己的一部分影子，始终陪伴在你的身旁，就会产生一种安心的感觉。这是一个很普遍的现象，小到小
学，总有一群男孩一下课就冲出教室去抢占乒乓球台，因为他们都热爱着乒乓球；也有一群女孩在讨论自己的新衣服，因为这让她们变得更漂亮，这几乎是所有
女性朋友的爱好吧；大到弯腰驼背的老人，我们经常会看见一群老人在公园里下象棋，跳广场舞，或者打太极，没错吧！其中，让我们感受最为深刻的是，有室
友或者同班同学同你来自一个地区，你会油然而生一种亲切感，没错吧！因为乒乓球，所以那群小男孩们
才有可能成为哥们；因为喜欢美，所以小女孩们才有可能成为闺蜜；因为有了名为 “共有特征” 的钥匙，我们才会与其他人发生交集，之后有机会共同编写一
个属于双方专有的故事，最后，拿着这把钥匙，打开对方的心扉。能做到最后一步，两人算是好朋友或者知己了吧！
    上面提到了共有特征的这个说法，可能会很迷糊。但是仔细推敲一下，上面我提到了两大类的共有特征。一是，热爱乒乓球，下象棋，跳广场舞这种现实而
又具体的形式，例如：喜欢编程，痴心物理，醉心唐诗宋词等；另一种则是爱美，这种现实却很抽象的形式，例如：渴望成功，爱国，成为英雄等，这种让人
难以具体描述却又真实存在的地方，如果你理解了，那就算不上了。如果在第一类特征上多问一个为什么的话，那就变成第二类特征了。在这儿就不说了，不然
可能就看不懂了，思考也是一个很重要的第二类特征嘛！
    共有特征发挥着很重要的作用。拿第一类来说的话，就会产生一种物理类聚，人以群分的现象了，肯定是既有积极作用又有消极作用了。大学里面的各种各
样的社团就是人以群分的典型例子了，它将各个有着共同爱好的人聚在了一起，你也可以从中找到自己的归宿，之后就不难想象了，你同一群有着共同爱好甚至
目标的人待在一起，你可以从他们身上学习到新的东西，进而感受到快乐和成就感了！还有一种可能就是，进去了之后，自己原有的
的爱好反而被消磨殆尽了，这就成了一个反面例子了。如果是第二类的话，我觉得作用是有深远影响的，而且是不可预测。最最最典型的就是中国人独有的爱国
这一条了，这是每一个中国人的特征，也是面对入侵时，全国人民能团结一致，
一致对外的基础，当然能将这种潜意识的特征放大的毛主席，毫无疑问的来说，是了不起的。为了进一步说明这种不可预测的性质，我想再讲一个初中数学老师讲的一个故
事，我的记忆也比较模糊了，我也不清楚为什么现在还有印象。大致内容是，一家公司派出老陈同另外一家公司谈生意，老陈是一位喜欢古典文学的人，一有空
就会专研古典书籍，尤其喜欢《道德经》《孟子》和《春秋》最近又开始捣鼓《易经》了。谁知在这场谈判中对方迟到了，老陈就抓紧时间拿出了自己随身携带
的《易经》开始研究了起来。谁知没过多久对方就来了，一见老陈在捣鼓《易经》，就开始询问对方还喜欢什么书籍。没错，对方也喜欢研读古典书籍，当一提到《道德经》，对方就激动了起来
，两人一发不可收拾的聊了起来，完全忘记了还有生意要谈这回事儿。当意识到谈判的时间快要结束时，双方很迅速，满意的完成了这场谈判......大致内容是这样。因为第二种
特征难以被意识，理解，它的消极与积极意义，我目前也很难划分，更无法举例说明了，但是我初步认为积极意义远大于消极影响的。
    最后，关于如何培养这种共有特征。问自己两个问题。你要与其他人培养什么样的共有特征？一起玩一款游戏，还是待在图书馆学习之类的。它是哪种形式的？是
具体可描述的，还是抽象不容易理解的？不管怎样，关键（key）还是在于坚持，如果问什么天赋是最重要的话，毫无疑问是坚持。但是，这并不意味着坚持就一
定有效果，搞清楚前面两个问题后再来思索坚持的问题，相对于盲目坚持这种形式，搞清楚目的和形式后坚持，这样效率更高，更容易出效果。









1) 共有特诊的两种方式
2) 共有特征的作用(积极和消极)
3) 以及如何培养和加深这种特征
#     先让我们来看一组词语吧！都是特别浪漫的词。一见钟情，日久生情。有人相信一见钟情，不相信日久生情；有人相信日久生情，不相信一见钟情。但是，我相信，他们俩都没错。为什么这么说呢？
#     来看看第一种情况吧——一见钟情。先说结果吧，能够一见钟情的人，有很好的眼力以及洞察力，也可能与第六感有关。可能本人并不会承认，说得更准确一点就是本人是没有多少自觉的。这其实不难理解，相当于你问一个素描高
# 手，素描一个人难吗？答案显而易见吧！与这是一个道理。为了进一步阐述，在这儿我想引入论语中的一段对话：“子禽问于子贡曰：夫子至于是邦也，必闻其政，求之与，抑与之与？”子贡曰：“夫子温、良、恭、俭、让以得之。夫子
# 之求之也，其诸异乎人之求之与？”这句话的大致意思是这样：子禽问子贡说：“老师到了一个国家，总是要了解那个国家的政事，是老师求来的呢，还是别人主动告诉他的呢？”子贡说：“老师是靠温顺、善良、恭敬、俭朴、谦让求得
# 的，老师了解一个国家政事的方式，大概与别人不同吧？“ 在这儿很明白清楚的说明了孔子与其他人的不同，类比的话，就是能一见钟情的人观察和看待事物的方式与大多数人不同，虽然一见钟情的人很少，但还是有，不然怎么会诞生
# 这浪漫的词。

* 《辉煌中国》6
  在开放过程中体现出的海纳百川，有容乃大的人文精神，以及如今的中国、中国人在国际舞台上发挥着举足轻重的作用和强烈的自信。中国已经走在了复兴的道路上，中国也必定能够实现复兴的重任，再次屹立于世界之巅。这是我在看完辉煌中国第六集开放中国后最深刻的感受。我们的改革开放，不是利己主义的，是共商、共建、共享的，这就注定了改革开放道路的理念，一定是正确的，令人信服的，有说服力的。我们看中的不仅仅是自己和当下，更是预示到了人类的未来。我们的改革开放，不仅要让自己过得好，也要让别人过得好。这一理念更彰显了中国致力于消除阶级，维护世界和平的意志。影片结尾，更是展现了中国人不管走到哪了都更加自信了，祖国越来越强盛了的事实。一张中国护照的含金量是，不管你在什么地方，遇到什么情况，它都能带你安全回家。浩渺行无极，扬帆但信风。让我们充满自信和勇气，一起投身于中国伟大复兴的历史重任中去吧！

* 形式与政策１

　　　班内课
* 形式与政策２

                               劳模精神的社会价值

   提到劳模精神的社会价值，几乎每个人第一时间会想到核心价值观，这没什么不对。其实，大力弘扬劳模精神的背后，还有更深层的一面正在被影响——社会风气。

   社会风气是一种人们约定俗成的一种行为，也就是俗称的“风俗”。社会核心价值观与社会风气有着紧密的联系，两者相辅相成，人们有着什么样的价值观，就会形成什么样的社会风气。社会风气的影响很广，小到影响个人的仕途，大到影响一个国家的前途命运。例如：魏晋时期，文人不再谈论文学，难道是因为他们对文学没兴趣了吗？不是的，这是由于统治阶级对文人的迫害，致使他们不敢发表言论，否则很容易引来杀身之祸。文人不敢谈论政治，更不愿谈论文学，于是便掀起了一场谈玄的社会“潮流”，也就有了这样的情景。白天，大家在一间小屋子里窃窃私语，关好门窗，密不透风，显得神神秘秘的，担心别人看见，听见。仔细的观察，才发现他们谈论的却是不切实际的玄学。社会风气就好比作土壤，土壤的好坏和肥沃程度，就决定了社会价值观的正常与否和影响范围。魏晋时期，文人谈玄的风气一直在不断的蔓延，壮大，渐渐的就形成了这样一种社会风气，这个“温床”又诱使更多的人加入谈玄的大军之中，谈玄就成为了那个时期社会的一张名片。谈玄的社会风气揭示了当时社会的怪异，也正是文人搅动了整个社会怪异的气氛。文人自身显得十分古怪，他们不再谈论文学，睁眼闭眼都是在谈论玄学。最后，整个魏晋时期不过两百年时间就终结了。虽说魏晋时期过去了，但那个时候的社会风气产生的影响是极其深远的，直到中唐时朝，唐宋八大家之一的韩愈为了改变文坛一滩死水的状况，由此掀起了一场古文运动，这时文学创作才显现出了新的生命力。这段长达五百多年的社会风气中的怪象才渐渐退出了历史舞台。从中可以看出社会风气对社会的影响的是极其深远的，为什么社会风气的影响如此深远，显得如此重要呢？

   这个问题我们可以通过一位诗人的人生经历得到证明，他就是生活在唐由盛转衰时期的诗圣——杜甫。杜甫的一生颠沛流离，可谓阅经世间百态。他的诸多作品都反映出了民生的疾苦和社会的动荡不安。杜甫经历了安史之乱山河破碎的悲痛，也亲眼看见了人们陷入水深火热的痛苦，自己更是过着四处逃亡的生活，作为那个时代的亲历者，他心中仍怀抱着“致君尧舜上，再使风俗淳”的政治理想。杜甫将社会风气当作重要的一环，这其中也一定有着他自己的考量。

   如今，是一个大力宣传劳模精神的时代。我想，其更深层的社会价值是形成一种人人求上进，求创新，求实现“中国梦”的社会风气，以此为土壤，引导下一代，为祖国的伟大复兴提供得天独厚的社会环境。让这一股风，轻抚神州大地，绽放新的生命力。

* 形式与政策３

                                                                   中国梦，我的梦

   实现中华民族伟大复兴的中国梦是习近平在中国共产党第十九次全国代表大会报告上提出的。中国梦不仅是中国的，也是世界的。中国梦与人类追求和平与发展的梦想相一致，是开放、包容、共享的梦。作为生在此时代背景的大学生，我们有责任与义务，为实现民族复兴贡献自己微薄的力量——实现自己的梦想。

   树立远大的志向。引用《史记》中陈涉中的一句话，“燕雀安知鸿鹄之志哉”。宁做鸿鹄，不做燕雀，拒绝平庸。因为它能让我看得更多，看得更远，更是我砥砺前行的动力。在困难面前，它迫使我不停的思考，反复地质问自己，我现在该做什么？我该怎么做？怎样才能做得更好？在无数次的质问之声中，最终得到了一份算不上优秀的答案。就像这样一次又一次的翻过一道又一道的坎，我得到了一套能应对无数问题的解决方案，这就是积累，这成为了我一生中最宝贵的财富。在今后的生命历程里，我不停的扩充着它，不停的使用它，不停的优化它。于是，每当新的问题，我都能应对自如，拿出不同的解决方案，并从中选择最切实可行的一个。或许有一天正午，天气晴好，微风轻拂，坐在椅子上的我决定小憩一会，喝喝茶，再看看这个世界的时候，这个世界出现了一些奇妙的变化，对，那就是未来。我应该树立远大的志向，因为它能给我一种超能力，让我走得更远，看的更多，看得更透。

   脚踏实地，实事求是。求实，这是一个永恒的话题，如何做到这一点，我想引用《论语》中的一句“吾日三省吾身：为人谋而不忠乎？与朋友交而不信乎？传不习乎？”这是实现自己梦想过程中最重要的一环。这能让我清楚地认识到自己的优势和劣势，只有在此基础上我才能发挥自己的优势以及思考如何更大限度的利用自己的优势，弥补自己的短板。

   面对全球化，保持开放，宽容的态度。世界已经身处经济全球化的浪潮中，任何国家都不可能独善其身，根据十九大报告指出，祖国将继续全面深化改革，这代表着祖国开放的大门将永远敞开，并且越来越大。因为历史告诉我，任何一个开放的时代，都是一个繁荣昌盛的时期。古有唐朝盛世的神话，今有美国迅速崛起的传奇。它们有着一个共同的特点，比以往任何时代都更加开放。我要紧跟时代的步伐，共同创造新的盛世。
* 形式与政策４

　　　　　　　　　　　　　　　　　　　　　　　　　　谈谈996

    最近，程序员界出了个新闻，有人在知名代码托管平台GitHub上发起了一个名为“996.ICU”的项目，以此抵制996工作制。此举立即得到大批程序员响应。所谓的996是指从每天上午9点工作到晚上9点，每周工作6天，“996.ICU”意为“工作996，生病ICU”。对此，我想谈谈自己的一些看法。

   首先大家一定要清楚一条，996是违法的。具体可查阅《中华人民共和国劳动法》第四章第三十六条规定。事发之后，有个有趣的反应，国内的各个浏览器都封禁了该项目网页。这一举动，很容易让人产生怀疑，释放出了做贼心虚的信号。其中，大家对996的最大分歧是钱没有给到位的问题。“996”工作制的周工作时间为最低12x6 = 72小时。中国大陆工时规管现况(标准工时)： 一天工作时间为8小时，平均每周工时不超过40小时；加班上限为一天3小时及一个月36小时，逾时工作薪金不低于平日工资的150%。而一周最高工时则为48小时。平均每月计薪天数为21.75天。按照劳动法规定，996工作制下只有有到当前工资的2.275倍，才在经济账上不吃亏。如果钱到位了，可能也就没这么大分歧了，也不会出现这个社会热点问题了。然而，现实却是，加完班根本没有加班费，做得不好，还面临着被裁的风险。

   支持996的马云说：“996是巨大的福气”还说 “每个人都必须有拼搏精神”那么第一个问题来了，管理阶层有为员工的拼搏买下所有的单吗？我臆想到了他们会说的另外一套说辞，你的拼搏提升了你自己的能力，这样的回报还不够吗？在这里我要强调的是，通过个人的拼搏由此提高了个人的能力与由于个人拼搏所带来的实际效益是紧密联系的，个人能力的提升只是拼搏带来的一部分收益，两者要分开看，说得现实一点儿，难道你当初的拼搏不是为了那一部分实际效益吗？不对，绝大多数人的拼搏都是为了那一部分实际效益，并不关心个人能力是否有所提升，所以当管理阶层说提升了个人能力的回报还不满足时，就显得手足无措、还为自己的贪得无厌而良心受到谴责。管理阶层也就怀着这样的“正当”心态理所当然的夺走了你的实际效益。你为什么要为这家公司，企业拼搏？难道是仅仅要提升个人的能力，不为了那一份实际效益吗？996工作制，剥夺了员工很大一部分的实际效益，也就是当前工资的1.275倍的工资。第二个问题，管理阶层有将企业的理念，或者叫使命，融入到大多数员工的生命里吗？管理阶层永远只有少部分的人，绝大多数全是员工。马云说，进入阿里是要改变自己、帮助别人、实现使命。在这个动不动就开除，视员工为抹布，又尤其是程序员，说换就换的年代，这样的理念只是在一个昏暗的角落散发着余晖吧！以为招收新的员工就是注入了新鲜血液，管理阶层每一年又注入了多少新鲜血液呢？最终怀着使命感完成工作的人，大概全是管理阶层的人了吧。管理阶层自以为所有的员工都是怀着使命感在工作，没有做到“不患人之不知己，患不知人也”。领导力十原则里有这样一条原则，一个合格的领导者会培养自己接班人。这种轻易开除员工的做法，就是在拒绝新的接班人，也是企业开始走向封闭，最终被内部的腐败问题蚕食的开始。

   由此引申出来一个问题，奋斗与生活之间如何选择？奋斗其实就是不断学习的过程。我想引用孔子的一句话来说明两者之间的关系，“弟子入则孝，出则悌，谨而信，泛爱众，而亲仁。行有余力，则以学文”。
